version: "3"
services:
  directus:
    image: directus/directus:10.8.3
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      KEY: "${DIRECTUS_KEY}"
      SECRET: "${DIRECTUS_SECRET}"
      ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASSWORD}"
      DB_CLIENT: "pg"
      DB_CONNECTION_STRING: "DB_CONNECTION_STRING"
      # DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: true



      # Add more from the tutorial
      # Add for s3, ie no local?